"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-01-15 00:00:00
"""
from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    # The full DDL is created by SQLAlchemy metadata via `Base.metadata.create_all`
    # in test envs. Production migrations should be generated by
    # `alembic revision --autogenerate` after models stabilize. This placeholder
    # documents the initial migration slot and enables trigram + citext up front.


def downgrade() -> None:
    pass
