/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAdminsRouteImport } from './routes/_authenticated/admins'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedBulkImportRouteImport } from './routes/_authenticated/bulk-import'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGenerateRouteImport } from './routes/_authenticated/generate'
import { Route as AuthenticatedIdCardsRouteImport } from './routes/_authenticated/id-cards'
import { Route as AuthenticatedSchoolsRouteImport } from './routes/_authenticated/schools'
import { Route as AuthenticatedTeachersRouteImport } from './routes/_authenticated/teachers'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students/index'
import { Route as AuthenticatedStudentsIdRouteImport } from './routes/_authenticated/students/$id'
import { Route as AuthenticatedTemplatesIndexRouteImport } from './routes/_authenticated/templates/index'
import { Route as AuthenticatedTemplatesIdRouteImport } from './routes/_authenticated/templates/$id'
import { Route as ApiPublicAuthBootstrapRouteImport } from './routes/api/public/auth/bootstrap'
import { Route as ApiPublicAuthLoginRouteImport } from './routes/api/public/auth/login'
import { Route as ApiPublicAuthSignupTeacherRouteImport } from './routes/api/public/auth/signup-teacher'
import { Route as ApiPublicV1StudentsRouteImport } from './routes/api/public/v1/students'
import { Route as ApiPublicV1AuthLoginRouteImport } from './routes/api/public/v1/auth/login'
import { Route as ApiPublicV1AuthRefreshRouteImport } from './routes/api/public/v1/auth/refresh'
import { Route as ApiPublicV1SchoolsAvailableRouteImport } from './routes/api/public/v1/schools/available'
import { Route as ApiPublicV1AuthSignupTeacherRouteImport } from './routes/api/public/v1/auth/signup/teacher'
import { Route as ApiPublicV1StudentsIdPhotoRouteImport } from './routes/api/public/v1/students/$id/photo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminsRoute = AuthenticatedAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBulkImportRoute = AuthenticatedBulkImportRouteImport.update({
  id: '/bulk-import',
  path: '/bulk-import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGenerateRoute = AuthenticatedGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIdCardsRoute = AuthenticatedIdCardsRouteImport.update({
  id: '/id-cards',
  path: '/id-cards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchoolsRoute = AuthenticatedSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeachersRoute = AuthenticatedTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesIndexRoute =
  AuthenticatedTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesIdRoute =
  AuthenticatedTemplatesIdRouteImport.update({
    id: '/templates/$id',
    path: '/templates/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicAuthBootstrapRoute = ApiPublicAuthBootstrapRouteImport.update({
  id: '/api/public/auth/bootstrap',
  path: '/api/public/auth/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthLoginRoute = ApiPublicAuthLoginRouteImport.update({
  id: '/api/public/auth/login',
  path: '/api/public/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthSignupTeacherRoute =
  ApiPublicAuthSignupTeacherRouteImport.update({
    id: '/api/public/auth/signup-teacher',
    path: '/api/public/auth/signup-teacher',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1StudentsRoute = ApiPublicV1StudentsRouteImport.update({
  id: '/api/public/v1/students',
  path: '/api/public/v1/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AuthLoginRoute = ApiPublicV1AuthLoginRouteImport.update({
  id: '/api/public/v1/auth/login',
  path: '/api/public/v1/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AuthRefreshRoute = ApiPublicV1AuthRefreshRouteImport.update({
  id: '/api/public/v1/auth/refresh',
  path: '/api/public/v1/auth/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1SchoolsAvailableRoute =
  ApiPublicV1SchoolsAvailableRouteImport.update({
    id: '/api/public/v1/schools/available',
    path: '/api/public/v1/schools/available',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1AuthSignupTeacherRoute =
  ApiPublicV1AuthSignupTeacherRouteImport.update({
    id: '/api/public/v1/auth/signup/teacher',
    path: '/api/public/v1/auth/signup/teacher',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1StudentsIdPhotoRoute =
  ApiPublicV1StudentsIdPhotoRouteImport.update({
    id: '/$id/photo',
    path: '/$id/photo',
    getParentRoute: () => ApiPublicV1StudentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admins': typeof AuthenticatedAdminsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bulk-import': typeof AuthenticatedBulkImportRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/id-cards': typeof AuthenticatedIdCardsRoute
  '/schools': typeof AuthenticatedSchoolsRoute
  '/teachers': typeof AuthenticatedTeachersRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/templates/$id': typeof AuthenticatedTemplatesIdRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
  '/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/api/public/auth/bootstrap': typeof ApiPublicAuthBootstrapRoute
  '/api/public/auth/login': typeof ApiPublicAuthLoginRoute
  '/api/public/auth/signup-teacher': typeof ApiPublicAuthSignupTeacherRoute
  '/api/public/v1/students': typeof ApiPublicV1StudentsRouteWithChildren
  '/api/public/v1/auth/login': typeof ApiPublicV1AuthLoginRoute
  '/api/public/v1/auth/refresh': typeof ApiPublicV1AuthRefreshRoute
  '/api/public/v1/schools/available': typeof ApiPublicV1SchoolsAvailableRoute
  '/api/public/v1/auth/signup/teacher': typeof ApiPublicV1AuthSignupTeacherRoute
  '/api/public/v1/students/$id/photo': typeof ApiPublicV1StudentsIdPhotoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admins': typeof AuthenticatedAdminsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bulk-import': typeof AuthenticatedBulkImportRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/generate': typeof AuthenticatedGenerateRoute
  '/id-cards': typeof AuthenticatedIdCardsRoute
  '/schools': typeof AuthenticatedSchoolsRoute
  '/teachers': typeof AuthenticatedTeachersRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/templates/$id': typeof AuthenticatedTemplatesIdRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/templates': typeof AuthenticatedTemplatesIndexRoute
  '/api/public/auth/bootstrap': typeof ApiPublicAuthBootstrapRoute
  '/api/public/auth/login': typeof ApiPublicAuthLoginRoute
  '/api/public/auth/signup-teacher': typeof ApiPublicAuthSignupTeacherRoute
  '/api/public/v1/students': typeof ApiPublicV1StudentsRouteWithChildren
  '/api/public/v1/auth/login': typeof ApiPublicV1AuthLoginRoute
  '/api/public/v1/auth/refresh': typeof ApiPublicV1AuthRefreshRoute
  '/api/public/v1/schools/available': typeof ApiPublicV1SchoolsAvailableRoute
  '/api/public/v1/auth/signup/teacher': typeof ApiPublicV1AuthSignupTeacherRoute
  '/api/public/v1/students/$id/photo': typeof ApiPublicV1StudentsIdPhotoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admins': typeof AuthenticatedAdminsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/bulk-import': typeof AuthenticatedBulkImportRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/generate': typeof AuthenticatedGenerateRoute
  '/_authenticated/id-cards': typeof AuthenticatedIdCardsRoute
  '/_authenticated/schools': typeof AuthenticatedSchoolsRoute
  '/_authenticated/teachers': typeof AuthenticatedTeachersRoute
  '/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute
  '/_authenticated/templates/$id': typeof AuthenticatedTemplatesIdRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
  '/_authenticated/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/api/public/auth/bootstrap': typeof ApiPublicAuthBootstrapRoute
  '/api/public/auth/login': typeof ApiPublicAuthLoginRoute
  '/api/public/auth/signup-teacher': typeof ApiPublicAuthSignupTeacherRoute
  '/api/public/v1/students': typeof ApiPublicV1StudentsRouteWithChildren
  '/api/public/v1/auth/login': typeof ApiPublicV1AuthLoginRoute
  '/api/public/v1/auth/refresh': typeof ApiPublicV1AuthRefreshRoute
  '/api/public/v1/schools/available': typeof ApiPublicV1SchoolsAvailableRoute
  '/api/public/v1/auth/signup/teacher': typeof ApiPublicV1AuthSignupTeacherRoute
  '/api/public/v1/students/$id/photo': typeof ApiPublicV1StudentsIdPhotoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admins'
    | '/analytics'
    | '/bulk-import'
    | '/dashboard'
    | '/generate'
    | '/id-cards'
    | '/schools'
    | '/teachers'
    | '/students/$id'
    | '/templates/$id'
    | '/students/'
    | '/templates/'
    | '/api/public/auth/bootstrap'
    | '/api/public/auth/login'
    | '/api/public/auth/signup-teacher'
    | '/api/public/v1/students'
    | '/api/public/v1/auth/login'
    | '/api/public/v1/auth/refresh'
    | '/api/public/v1/schools/available'
    | '/api/public/v1/auth/signup/teacher'
    | '/api/public/v1/students/$id/photo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admins'
    | '/analytics'
    | '/bulk-import'
    | '/dashboard'
    | '/generate'
    | '/id-cards'
    | '/schools'
    | '/teachers'
    | '/students/$id'
    | '/templates/$id'
    | '/students'
    | '/templates'
    | '/api/public/auth/bootstrap'
    | '/api/public/auth/login'
    | '/api/public/auth/signup-teacher'
    | '/api/public/v1/students'
    | '/api/public/v1/auth/login'
    | '/api/public/v1/auth/refresh'
    | '/api/public/v1/schools/available'
    | '/api/public/v1/auth/signup/teacher'
    | '/api/public/v1/students/$id/photo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admins'
    | '/_authenticated/analytics'
    | '/_authenticated/bulk-import'
    | '/_authenticated/dashboard'
    | '/_authenticated/generate'
    | '/_authenticated/id-cards'
    | '/_authenticated/schools'
    | '/_authenticated/teachers'
    | '/_authenticated/students/$id'
    | '/_authenticated/templates/$id'
    | '/_authenticated/students/'
    | '/_authenticated/templates/'
    | '/api/public/auth/bootstrap'
    | '/api/public/auth/login'
    | '/api/public/auth/signup-teacher'
    | '/api/public/v1/students'
    | '/api/public/v1/auth/login'
    | '/api/public/v1/auth/refresh'
    | '/api/public/v1/schools/available'
    | '/api/public/v1/auth/signup/teacher'
    | '/api/public/v1/students/$id/photo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicAuthBootstrapRoute: typeof ApiPublicAuthBootstrapRoute
  ApiPublicAuthLoginRoute: typeof ApiPublicAuthLoginRoute
  ApiPublicAuthSignupTeacherRoute: typeof ApiPublicAuthSignupTeacherRoute
  ApiPublicV1StudentsRoute: typeof ApiPublicV1StudentsRouteWithChildren
  ApiPublicV1AuthLoginRoute: typeof ApiPublicV1AuthLoginRoute
  ApiPublicV1AuthRefreshRoute: typeof ApiPublicV1AuthRefreshRoute
  ApiPublicV1SchoolsAvailableRoute: typeof ApiPublicV1SchoolsAvailableRoute
  ApiPublicV1AuthSignupTeacherRoute: typeof ApiPublicV1AuthSignupTeacherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admins': {
      id: '/_authenticated/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AuthenticatedAdminsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bulk-import': {
      id: '/_authenticated/bulk-import'
      path: '/bulk-import'
      fullPath: '/bulk-import'
      preLoaderRoute: typeof AuthenticatedBulkImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate': {
      id: '/_authenticated/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof AuthenticatedGenerateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/id-cards': {
      id: '/_authenticated/id-cards'
      path: '/id-cards'
      fullPath: '/id-cards'
      preLoaderRoute: typeof AuthenticatedIdCardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schools': {
      id: '/_authenticated/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof AuthenticatedSchoolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers': {
      id: '/_authenticated/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AuthenticatedTeachersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/$id': {
      id: '/_authenticated/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AuthenticatedStudentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/': {
      id: '/_authenticated/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AuthenticatedTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/$id': {
      id: '/_authenticated/templates/$id'
      path: '/templates/$id'
      fullPath: '/templates/$id'
      preLoaderRoute: typeof AuthenticatedTemplatesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/auth/bootstrap': {
      id: '/api/public/auth/bootstrap'
      path: '/api/public/auth/bootstrap'
      fullPath: '/api/public/auth/bootstrap'
      preLoaderRoute: typeof ApiPublicAuthBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/login': {
      id: '/api/public/auth/login'
      path: '/api/public/auth/login'
      fullPath: '/api/public/auth/login'
      preLoaderRoute: typeof ApiPublicAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/signup-teacher': {
      id: '/api/public/auth/signup-teacher'
      path: '/api/public/auth/signup-teacher'
      fullPath: '/api/public/auth/signup-teacher'
      preLoaderRoute: typeof ApiPublicAuthSignupTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/students': {
      id: '/api/public/v1/students'
      path: '/api/public/v1/students'
      fullPath: '/api/public/v1/students'
      preLoaderRoute: typeof ApiPublicV1StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/auth/login': {
      id: '/api/public/v1/auth/login'
      path: '/api/public/v1/auth/login'
      fullPath: '/api/public/v1/auth/login'
      preLoaderRoute: typeof ApiPublicV1AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/auth/refresh': {
      id: '/api/public/v1/auth/refresh'
      path: '/api/public/v1/auth/refresh'
      fullPath: '/api/public/v1/auth/refresh'
      preLoaderRoute: typeof ApiPublicV1AuthRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/schools/available': {
      id: '/api/public/v1/schools/available'
      path: '/api/public/v1/schools/available'
      fullPath: '/api/public/v1/schools/available'
      preLoaderRoute: typeof ApiPublicV1SchoolsAvailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/auth/signup/teacher': {
      id: '/api/public/v1/auth/signup/teacher'
      path: '/api/public/v1/auth/signup/teacher'
      fullPath: '/api/public/v1/auth/signup/teacher'
      preLoaderRoute: typeof ApiPublicV1AuthSignupTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/students/$id/photo': {
      id: '/api/public/v1/students/$id/photo'
      path: '/$id/photo'
      fullPath: '/api/public/v1/students/$id/photo'
      preLoaderRoute: typeof ApiPublicV1StudentsIdPhotoRouteImport
      parentRoute: typeof ApiPublicV1StudentsRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminsRoute: typeof AuthenticatedAdminsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBulkImportRoute: typeof AuthenticatedBulkImportRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGenerateRoute: typeof AuthenticatedGenerateRoute
  AuthenticatedIdCardsRoute: typeof AuthenticatedIdCardsRoute
  AuthenticatedSchoolsRoute: typeof AuthenticatedSchoolsRoute
  AuthenticatedTeachersRoute: typeof AuthenticatedTeachersRoute
  AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute
  AuthenticatedTemplatesIdRoute: typeof AuthenticatedTemplatesIdRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
  AuthenticatedTemplatesIndexRoute: typeof AuthenticatedTemplatesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminsRoute: AuthenticatedAdminsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBulkImportRoute: AuthenticatedBulkImportRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGenerateRoute: AuthenticatedGenerateRoute,
  AuthenticatedIdCardsRoute: AuthenticatedIdCardsRoute,
  AuthenticatedSchoolsRoute: AuthenticatedSchoolsRoute,
  AuthenticatedTeachersRoute: AuthenticatedTeachersRoute,
  AuthenticatedStudentsIdRoute: AuthenticatedStudentsIdRoute,
  AuthenticatedTemplatesIdRoute: AuthenticatedTemplatesIdRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
  AuthenticatedTemplatesIndexRoute: AuthenticatedTemplatesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicV1StudentsRouteChildren {
  ApiPublicV1StudentsIdPhotoRoute: typeof ApiPublicV1StudentsIdPhotoRoute
}

const ApiPublicV1StudentsRouteChildren: ApiPublicV1StudentsRouteChildren = {
  ApiPublicV1StudentsIdPhotoRoute: ApiPublicV1StudentsIdPhotoRoute,
}

const ApiPublicV1StudentsRouteWithChildren =
  ApiPublicV1StudentsRoute._addFileChildren(ApiPublicV1StudentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicAuthBootstrapRoute: ApiPublicAuthBootstrapRoute,
  ApiPublicAuthLoginRoute: ApiPublicAuthLoginRoute,
  ApiPublicAuthSignupTeacherRoute: ApiPublicAuthSignupTeacherRoute,
  ApiPublicV1StudentsRoute: ApiPublicV1StudentsRouteWithChildren,
  ApiPublicV1AuthLoginRoute: ApiPublicV1AuthLoginRoute,
  ApiPublicV1AuthRefreshRoute: ApiPublicV1AuthRefreshRoute,
  ApiPublicV1SchoolsAvailableRoute: ApiPublicV1SchoolsAvailableRoute,
  ApiPublicV1AuthSignupTeacherRoute: ApiPublicV1AuthSignupTeacherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
